import { calculateEffectivePrice } from './effective-price';
import { CanonicalProduct, RetailOffer, RetailOfferInput } from './types';

export const canonicalProducts: CanonicalProduct[] = [
  {
    product_id: 'black-hawk-indoor-chicken-rice-2000g',
    slug: 'black-hawk-indoor-chicken-rice-2000g',
    product_name: 'Indoor Chicken & Rice',
    brand_name: 'Black Hawk',
    species: 'CAT',
    pack_size_g: 2000,
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk',
    formula_tokens: ['indoor'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'black-hawk-indoor-chicken-rice-4000g',
    slug: 'black-hawk-indoor-chicken-rice-4000g',
    product_name: 'Indoor Chicken & Rice',
    brand_name: 'Black Hawk',
    species: 'CAT',
    pack_size_g: 4000,
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk',
    formula_tokens: ['indoor'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'black-hawk-indoor-chicken-rice-8000g',
    slug: 'black-hawk-indoor-chicken-rice-8000g',
    product_name: 'Indoor Chicken & Rice',
    brand_name: 'Black Hawk',
    species: 'CAT',
    pack_size_g: 8000,
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk',
    formula_tokens: ['indoor'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'black-hawk-original-chicken-2000g',
    slug: 'black-hawk-original-chicken-2000g',
    product_name: 'Original Chicken Dry Cat Food',
    brand_name: 'Black Hawk',
    species: 'CAT',
    pack_size_g: 2000,
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk+Original',
    formula_tokens: ['original'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'black-hawk-original-chicken-4000g',
    slug: 'black-hawk-original-chicken-4000g',
    product_name: 'Original Chicken Dry Cat Food',
    brand_name: 'Black Hawk',
    species: 'CAT',
    pack_size_g: 4000,
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk+Original',
    formula_tokens: ['original'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'black-hawk-original-chicken-12000g',
    slug: 'black-hawk-original-chicken-12000g',
    product_name: 'Original Chicken Dry Cat Food',
    brand_name: 'Black Hawk',
    species: 'CAT',
    pack_size_g: 12000,
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk+Original',
    formula_tokens: ['original'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'hills-science-diet-indoor-adult-2000g',
    slug: 'hills-science-diet-indoor-adult-2000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: "Hill's Science Diet",
    species: 'CAT',
    pack_size_g: 2000,
    primary_image_url: 'https://placehold.co/640x800/e9efe7/66725d?text=Hill%27s+Indoor',
    formula_tokens: ['indoor'],
    flavour_tokens: [],
  },
  {
    product_id: 'hills-science-diet-indoor-adult-4000g',
    slug: 'hills-science-diet-indoor-adult-4000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: "Hill's Science Diet",
    species: 'CAT',
    pack_size_g: 4000,
    primary_image_url: 'https://placehold.co/640x800/e9efe7/66725d?text=Hill%27s+Indoor',
    formula_tokens: ['indoor'],
    flavour_tokens: [],
  },
  {
    product_id: 'hills-science-diet-sensitive-stomach-skin-adult-chicken-3170g',
    slug: 'hills-science-diet-sensitive-stomach-skin-adult-chicken-3170g',
    product_name: 'Sensitive Stomach & Skin Adult Chicken Dry Cat Food',
    brand_name: "Hill's Science Diet",
    species: 'CAT',
    pack_size_g: 3170,
    primary_image_url: 'https://placehold.co/640x800/efe8de/7b6d5c?text=Hill%27s+Sensitive',
    formula_tokens: ['sensitive', 'stomach', 'skin'],
    flavour_tokens: ['chicken'],
  },
  {
    product_id: 'royal-canin-indoor-adult-2000g',
    slug: 'royal-canin-indoor-adult-2000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 2000,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/9a6c4f?text=Royal+Canin',
    formula_tokens: ['indoor'],
    flavour_tokens: [],
  },
  {
    product_id: 'royal-canin-indoor-adult-4000g',
    slug: 'royal-canin-indoor-adult-4000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 4000,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/9a6c4f?text=Royal+Canin',
    formula_tokens: ['indoor'],
    flavour_tokens: [],
  },
  {
    product_id: 'royal-canin-indoor-adult-10000g',
    slug: 'royal-canin-indoor-adult-10000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 10000,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/9a6c4f?text=Royal+Canin',
    formula_tokens: ['indoor'],
    flavour_tokens: [],
  },
  {
    product_id: 'royal-canin-fit-adult-2000g',
    slug: 'royal-canin-fit-adult-2000g',
    product_name: 'Fit Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 2000,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/9a6c4f?text=Royal+Canin+Fit',
    formula_tokens: ['fit'],
    flavour_tokens: [],
  },
  {
    product_id: 'royal-canin-fit-adult-4000g',
    slug: 'royal-canin-fit-adult-4000g',
    product_name: 'Fit Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 4000,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/9a6c4f?text=Royal+Canin+Fit',
    formula_tokens: ['fit'],
    flavour_tokens: [],
  },
  {
    product_id: 'royal-canin-light-weight-care-adult-1500g',
    slug: 'royal-canin-light-weight-care-adult-1500g',
    product_name: 'Light Weight Care Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 1500,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/a27a58?text=Royal+Canin+Light',
    formula_tokens: ['light', 'weight'],
    flavour_tokens: [],
  },
  {
    product_id: 'royal-canin-light-weight-care-adult-3000g',
    slug: 'royal-canin-light-weight-care-adult-3000g',
    product_name: 'Light Weight Care Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    species: 'CAT',
    pack_size_g: 3000,
    primary_image_url: 'https://placehold.co/640x800/f6ece2/a27a58?text=Royal+Canin+Light',
    formula_tokens: ['light', 'weight'],
    flavour_tokens: [],
  },
  {
    product_id: 'ziwi-peak-air-dried-mackerel-lamb-400g',
    slug: 'ziwi-peak-air-dried-mackerel-lamb-400g',
    product_name: 'Air-Dried Mackerel & Lamb',
    brand_name: 'Ziwi Peak',
    species: 'CAT',
    pack_size_g: 400,
    primary_image_url: 'https://placehold.co/640x800/f3ead9/5f6d57?text=Ziwi+Peak',
    formula_tokens: [],
    flavour_tokens: ['mackerel', 'lamb'],
  },
];

export const rawFixtureOffers: RetailOfferInput[] = [
  {
    product_id: 'black-hawk-indoor-chicken-rice-2000g',
    product_slug: 'black-hawk-indoor-chicken-rice-2000g',
    product_name: 'Indoor Chicken & Rice',
    brand_name: 'Black Hawk',
    retailer_name: 'Pet Circle',
    retailer_slug: 'pet-circle',
    market: 'AU',
    currency: 'AUD',
    product_url: 'https://www.petcircle.com.au/product/black-hawk-indoor-chicken-rice',
    pack_size_g: 2000,
    base_price: 33.99,
    sale_price: 31.99,
    member_price: 29.99,
    stock_status: 'IN_STOCK',
    promotion_text: 'Member price available after login',
    promotion_type: 'MEMBER_PRICE',
    last_checked_at: '2026-06-15T00:00:00.000Z',
    primary_image_url: 'https://placehold.co/640x800/efe8de/6a604f?text=Black+Hawk',
  },
  {
    product_id: 'black-hawk-indoor-chicken-rice-2000g',
    product_slug: 'black-hawk-indoor-chicken-rice-2000g',
    product_name: 'Indoor Chicken & Rice',
    brand_name: 'Black Hawk',
    retailer_name: 'Petbarn',
    retailer_slug: 'petbarn',
    market: 'AU',
    currency: 'AUD',
    product_url: 'https://www.petbarn.com.au/black-hawk-indoor-chicken-rice',
    pack_size_g: 2000,
    base_price: 32.99,
    coupon_price: 27.99,
    coupon_code: 'CAT5',
    minimum_spend: 80,
    stock_status: 'LOW_STOCK',
    promotion_text: 'Coupon available with minimum spend',
    promotion_type: 'COUPON',
    last_checked_at: '2026-06-15T01:00:00.000Z',
  },
  {
    product_id: 'black-hawk-indoor-chicken-rice-2000g',
    product_slug: 'black-hawk-indoor-chicken-rice-2000g',
    product_name: 'Indoor Chicken & Rice',
    brand_name: 'Black Hawk',
    retailer_name: 'NZ Pet Store',
    retailer_slug: 'nz-pet-store',
    market: 'NZ',
    currency: 'NZD',
    product_url: 'https://example.co.nz/black-hawk-indoor-chicken-rice',
    pack_size_g: 2000,
    base_price: 39.99,
    sale_price: 37.99,
    stock_status: 'IN_STOCK',
    promotion_text: 'NZ launch price',
    promotion_type: 'SALE',
    last_checked_at: '2026-06-15T02:00:00.000Z',
  },
  {
    product_id: 'royal-canin-indoor-adult-4000g',
    product_slug: 'royal-canin-indoor-adult-4000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    retailer_name: 'Pet Circle',
    retailer_slug: 'pet-circle',
    market: 'AU',
    currency: 'AUD',
    product_url: 'https://www.petcircle.com.au/product/royal-canin-indoor-adult-dry-cat-food',
    pack_size_g: 4000,
    base_price: 78.99,
    sale_price: 74.99,
    stock_status: 'IN_STOCK',
    promotion_text: 'Online sale',
    promotion_type: 'SALE',
    last_checked_at: '2026-06-15T00:30:00.000Z',
    primary_image_url: 'https://placehold.co/640x800/f6ece2/9a6c4f?text=Royal+Canin',
  },
  {
    product_id: 'royal-canin-indoor-adult-4000g',
    product_slug: 'royal-canin-indoor-adult-4000g',
    product_name: 'Indoor Adult Dry Cat Food',
    brand_name: 'Royal Canin',
    retailer_name: 'Petstock',
    retailer_slug: 'petstock',
    market: 'AU',
    currency: 'AUD',
    product_url: 'https://www.petstock.com.au/royal-canin-indoor-adult-dry-cat-food',
    pack_size_g: 4000,
    base_price: 71.99,
    stock_status: 'OUT_OF_STOCK',
    promotion_text: 'Temporarily unavailable',
    promotion_type: 'OTHER',
    last_checked_at: '2026-06-15T03:00:00.000Z',
  },
  {
    product_id: 'ziwi-peak-air-dried-mackerel-lamb-400g',
    product_slug: 'ziwi-peak-air-dried-mackerel-lamb-400g',
    product_name: 'Air-Dried Mackerel & Lamb',
    brand_name: 'Ziwi Peak',
    retailer_name: 'Pet Circle',
    retailer_slug: 'pet-circle',
    market: 'AU',
    currency: 'AUD',
    product_url: 'https://www.petcircle.com.au/product/ziwi-peak-air-dried-mackerel-lamb-cat',
    pack_size_g: 400,
    base_price: 45.49,
    stock_status: 'IN_STOCK',
    last_checked_at: '2026-06-15T00:15:00.000Z',
    primary_image_url: 'https://placehold.co/640x800/f3ead9/5f6d57?text=Ziwi+Peak',
  },
];

export const fixtureRetailOffers: RetailOffer[] = rawFixtureOffers.map((offer) => calculateEffectivePrice(offer));
