import { VerifiedProduct } from '../intelligence/types';

export const verifiedProducts: VerifiedProduct[] = [
  {
    id: 'ziwi-peak-mackerel-lamb',
    slug: 'ziwi-peak-air-dried-mackerel-lamb',
    name: 'Air-Dried Mackerel & Lamb',
    brand: 'Ziwi Peak',
    species: 'CAT',
    life_stage: 'ALL_LIFE_STAGES',
    verification_grade: 'GOLD',
    confidence: 96,
    market_availability: 'ACTIVE',
    nutrition: { protein: 38, fat: 30, fiber: 2, calories: 5500, moisture: 14, ash: 12, phosphorus: 1.4 },
    ingredients_normalized: ['Mackerel', 'Lamb', 'Lamb organ meat', 'Green mussel', 'Kelp', 'Minerals'],
    controversial_ingredients: [],
    suitability_tags: ['High Protein', 'Sensitive Stomach', 'Indoor Cat'],
    unit_price_aud_per_kg: 109.98,
  },
  {
    id: 'black-hawk-indoor-chicken-rice',
    slug: 'black-hawk-indoor-chicken-rice',
    name: 'Indoor Chicken & Rice',
    brand: 'Black Hawk',
    species: 'CAT',
    life_stage: 'ADULT',
    verification_grade: 'SILVER',
    confidence: 84,
    market_availability: 'ACTIVE',
    nutrition: { protein: 32, fat: 15, fiber: 5, calories: 3650, moisture: 10, ash: 8, phosphorus: 0.9 },
    ingredients_normalized: ['Chicken meal', 'Rice', 'Oats', 'Chicken fat', 'Beet pulp', 'Fish oil', 'Taurine'],
    controversial_ingredients: [],
    suitability_tags: ['Weight Control', 'Indoor Cat', 'Sensitive Stomach'],
    unit_price_aud_per_kg: 15.5,
  },
  {
    id: 'royal-canin-sterilised-37',
    slug: 'royal-canin-sterilised-37',
    name: 'Sterilised 37',
    brand: 'Royal Canin',
    species: 'CAT',
    life_stage: 'ADULT',
    verification_grade: 'SILVER',
    confidence: 88,
    market_availability: 'ACTIVE',
    nutrition: { protein: 37, fat: 12, fiber: 6.2, calories: 3509, moisture: 8, ash: 8.1, phosphorus: 0.85 },
    ingredients_normalized: ['Poultry protein', 'Vegetable fiber', 'Rice', 'Maize', 'Animal fat'],
    controversial_ingredients: ['Generic animal fat'],
    suitability_tags: ['Weight Control', 'Indoor Cat'],
    unit_price_aud_per_kg: 28.5,
  },
  {
    id: 'feline-natural-lamb-feast',
    slug: 'feline-natural-freeze-dried-lamb-feast',
    name: 'Freeze-Dried Lamb Feast',
    brand: 'Feline Natural',
    species: 'CAT',
    life_stage: 'ALL_LIFE_STAGES',
    verification_grade: 'GOLD',
    confidence: 94,
    market_availability: 'LIMITED',
    nutrition: { protein: 40, fat: 31, fiber: 2.5, calories: 4850, moisture: 8, ash: 9, phosphorus: 1.1 },
    ingredients_normalized: ['Lamb', 'Lamb organ meat', 'Flaxseed', 'Green mussel'],
    controversial_ingredients: [],
    suitability_tags: ['High Protein', 'Sensitive Stomach', 'Kitten Growth'],
    unit_price_aud_per_kg: 165.59,
  },
  {
    id: 'ivory-coat-lamb-brown-rice',
    slug: 'ivory-coat-lamb-brown-rice-adult-dog',
    name: 'Lamb & Brown Rice Adult',
    brand: 'Ivory Coat',
    species: 'DOG',
    life_stage: 'ADULT',
    verification_grade: 'BRONZE',
    confidence: 72,
    market_availability: 'ACTIVE',
    nutrition: { protein: 26, fat: 14, fiber: 4, calories: 3620, moisture: 10, ash: 7.5, phosphorus: 0.8 },
    ingredients_normalized: ['Lamb meal', 'Brown rice', 'Peas', 'Chicken fat', 'Beet pulp'],
    controversial_ingredients: ['Natural flavour'],
    suitability_tags: ['Sensitive Stomach', 'Adult Maintenance'],
    unit_price_aud_per_kg: 10.77,
  },
  {
    id: 'advance-puppy-growth',
    slug: 'advance-puppy-growth-chicken',
    name: 'Puppy Growth Chicken',
    brand: 'Advance',
    species: 'DOG',
    life_stage: 'PUPPY',
    verification_grade: 'SILVER',
    confidence: 82,
    market_availability: 'ACTIVE',
    nutrition: { protein: 30, fat: 19, fiber: 3.5, calories: 3920, moisture: 10, ash: 7.2, phosphorus: 1 },
    ingredients_normalized: ['Chicken meal', 'Rice', 'Maize gluten', 'Chicken fat', 'Fish oil'],
    controversial_ingredients: ['Maize gluten'],
    suitability_tags: ['Puppy Growth', 'High Protein'],
    unit_price_aud_per_kg: 16.33,
  },
];

export function findVerifiedProductByIdOrSlug(idOrSlug: string): VerifiedProduct | undefined {
  return verifiedProducts.find((product) => product.id === idOrSlug || product.slug === idOrSlug);
}
